### ISSUE TITLE
bug: pr status displayed incorrectly

### ISSUE THREAD

**Issue by frol** [NEAR-DevHub/race-of-sloths#141]
Currently, PR remains in the "waiting for scoring" for 24h even after score is given:

<img width="791" alt="image" src="https://github.com/user-attachments/assets/b332dcb2-aa17-47da-a386-0076f87d80a9">

<img width="955" alt="image" src="https://github.com/user-attachments/assets/66916bd2-a3c3-4b7c-92ff-59ef5cc1b671">

https://github.com/near/docs/pull/2082

**Comment by akorchyn** [comment]
Fixed in:
* https://github.com/NEAR-DevHub/race-of-sloths/commit/b6da880c36c37662733d7d8a9255b5e9a42dccb9
* https://github.com/NEAR-DevHub/race-of-sloths/commit/78d3aef0fd32b430a644c3f372afe0cb5a4d88db

Here are examples that run today and work just fine:
https://github.com/near/docs/pull/2130
https://github.com/near/cargo-near/pull/174
